// ── Clone type metadata ────────────────────────────────────────────────
export const CLONE_TYPES = {
  'Type-1': { label:'Type-1 · Exact',         color:'success', desc:'Identical code, only whitespace/comment differences',         highlight:'#10b981' },
  'Type-2': { label:'Type-2 · Renamed',        color:'accent',  desc:'Same structure, identifiers/literals renamed',                highlight:'#00d4ff' },
  'Type-3': { label:'Type-3 · Near-miss',      color:'amber',   desc:'Similar structure with added, removed, or modified statements', highlight:'#f59e0b' },
  'Type-4': { label:'Type-4 · Semantic',       color:'violet',  desc:'Different implementation, functionally equivalent',           highlight:'#8b5cf6' },
}

// ── Clone pairs (all four types) ──────────────────────────────────────
export const CLONE_PAIRS = [
  // ── TYPE 1 ──────────────────────────────────────────────────────────
  {
    id:1, type:'Type-1', similarity:0.99, crossLang:false,
    fileA:'utils/validator.py',  linesA:[12,22], cloneLinesA:[12,13,14,15,16,17,18,19,20,21,22],
    fileB:'helpers/validate.py', linesB:[5,15],  cloneLinesB:[5,6,7,8,9,10,11,12,13,14,15],
    desc:'Exact copy with minor whitespace differences',
    codeA: [
      { n:12, text:"def validate_email(email):" },
      { n:13, text:"    import re" },
      { n:14, text:"    pattern = r'^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$'" },
      { n:15, text:"    if not email or not isinstance(email, str):" },
      { n:16, text:"        return False" },
      { n:17, text:"    return bool(re.match(pattern, email.strip()))" },
      { n:18, text:"" },
      { n:19, text:"def validate_phone(phone):" },
      { n:20, text:"    pattern = r'^\\+?[1-9]\\d{1,14}$'" },
      { n:21, text:"    return bool(re.match(pattern, str(phone).strip()))" },
      { n:22, text:"" },
    ],
    codeB: [
      { n:5,  text:"def validate_email(email):" },
      { n:6,  text:"  import re" },
      { n:7,  text:"  pattern = r'^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$'" },
      { n:8,  text:"  if not email or not isinstance(email, str):" },
      { n:9,  text:"    return False" },
      { n:10, text:"  return bool(re.match(pattern, email.strip()))" },
      { n:11, text:"" },
      { n:12, text:"def validate_phone(phone):" },
      { n:13, text:"  pattern = r'^\\+?[1-9]\\d{1,14}$'" },
      { n:14, text:"  return bool(re.match(pattern, str(phone).strip()))" },
      { n:15, text:"" },
    ],
  },
  {
    id:2, type:'Type-1', similarity:1.0, crossLang:false,
    fileA:'models/user.py',    linesA:[44,54], cloneLinesA:[44,45,46,47,48,49,50,51,52,53,54],
    fileB:'api/user_copy.py',  linesB:[1,11],  cloneLinesB:[1,2,3,4,5,6,7,8,9,10,11],
    desc:'Perfect copy — no differences at all',
    codeA: [
      { n:44, text:"class UserSerializer:" },
      { n:45, text:"    def __init__(self, user):" },
      { n:46, text:"        self.user = user" },
      { n:47, text:"" },
      { n:48, text:"    def to_dict(self):" },
      { n:49, text:"        return {" },
      { n:50, text:"            'id': self.user.id," },
      { n:51, text:"            'email': self.user.email," },
      { n:52, text:"            'name': self.user.name," },
      { n:53, text:"        }" },
      { n:54, text:"" },
    ],
    codeB: [
      { n:1,  text:"class UserSerializer:" },
      { n:2,  text:"    def __init__(self, user):" },
      { n:3,  text:"        self.user = user" },
      { n:4,  text:"" },
      { n:5,  text:"    def to_dict(self):" },
      { n:6,  text:"        return {" },
      { n:7,  text:"            'id': self.user.id," },
      { n:8,  text:"            'email': self.user.email," },
      { n:9,  text:"            'name': self.user.name," },
      { n:10, text:"        }" },
      { n:11, text:"" },
    ],
  },

  // ── TYPE 2 ──────────────────────────────────────────────────────────
  {
    id:3, type:'Type-2', similarity:0.95, crossLang:false,
    fileA:'services/auth.py',   linesA:[30,42], cloneLinesA:[30,31,32,33,34,35,36,37,38,39,40,41,42],
    fileB:'core/security.py',   linesB:[18,30], cloneLinesB:[18,19,20,21,22,23,24,25,26,27,28,29,30],
    desc:'Same logic, variable and function names differ',
    codeA: [
      { n:30, text:"def hash_password(raw_password):" },
      { n:31, text:"    salt = bcrypt.gensalt(rounds=12)" },
      { n:32, text:"    hashed = bcrypt.hashpw(" },
      { n:33, text:"        raw_password.encode('utf-8'), salt" },
      { n:34, text:"    )" },
      { n:35, text:"    return hashed.decode('utf-8')" },
      { n:36, text:"" },
      { n:37, text:"def verify_password(raw_password, hashed_password):" },
      { n:38, text:"    return bcrypt.checkpw(" },
      { n:39, text:"        raw_password.encode('utf-8')," },
      { n:40, text:"        hashed_password.encode('utf-8')" },
      { n:41, text:"    )" },
      { n:42, text:"" },
    ],
    codeB: [
      { n:18, text:"def encrypt_pwd(plain_text):" },
      { n:19, text:"    s = bcrypt.gensalt(rounds=12)" },
      { n:20, text:"    encrypted = bcrypt.hashpw(" },
      { n:21, text:"        plain_text.encode('utf-8'), s" },
      { n:22, text:"    )" },
      { n:23, text:"    return encrypted.decode('utf-8')" },
      { n:24, text:"" },
      { n:25, text:"def check_pwd(plain_text, stored_hash):" },
      { n:26, text:"    return bcrypt.checkpw(" },
      { n:27, text:"        plain_text.encode('utf-8')," },
      { n:28, text:"        stored_hash.encode('utf-8')" },
      { n:29, text:"    )" },
      { n:30, text:"" },
    ],
  },
  {
    id:4, type:'Type-2', similarity:0.92, crossLang:true,
    fileA:'utils/calculator.py',  linesA:[8,20],  cloneLinesA:[8,9,10,11,12,13,14,15,16,17,18,19,20],
    fileB:'src/Calculator.java',  linesB:[22,34], cloneLinesB:[22,23,24,25,26,27,28,29,30,31,32,33,34],
    desc:'Structurally identical across Python and Java — only naming differs',
    codeA: [
      { n:8,  text:"def compute_total(items, tax_rate):" },
      { n:9,  text:"    subtotal = sum(item['price'] for item in items)" },
      { n:10, text:"    discount = subtotal * 0.10 if subtotal > 100 else 0" },
      { n:11, text:"    taxable = subtotal - discount" },
      { n:12, text:"    tax = taxable * tax_rate" },
      { n:13, text:"    total = taxable + tax" },
      { n:14, text:"    return {" },
      { n:15, text:"        'subtotal': subtotal," },
      { n:16, text:"        'discount': discount," },
      { n:17, text:"        'tax': tax," },
      { n:18, text:"        'total': total" },
      { n:19, text:"    }" },
      { n:20, text:"" },
    ],
    codeB: [
      { n:22, text:"public Map<String,Double> calculateBill(List<Item> products, double rate) {" },
      { n:23, text:"    double base = products.stream().mapToDouble(Item::getPrice).sum();" },
      { n:24, text:"    double rebate = base > 100 ? base * 0.10 : 0;" },
      { n:25, text:"    double net = base - rebate;" },
      { n:26, text:"    double vat = net * rate;" },
      { n:27, text:"    double grand = net + vat;" },
      { n:28, text:"    Map<String,Double> result = new HashMap<>();" },
      { n:29, text:"    result.put(\"base\", base);" },
      { n:30, text:"    result.put(\"rebate\", rebate);" },
      { n:31, text:"    result.put(\"vat\", vat);" },
      { n:32, text:"    result.put(\"grand\", grand);" },
      { n:33, text:"    return result;" },
      { n:34, text:"}" },
    ],
  },

  // ── TYPE 3 ──────────────────────────────────────────────────────────
  {
    id:5, type:'Type-3', similarity:0.84, crossLang:false,
    fileA:'api/pagination.py',   linesA:[3,22],  cloneLinesA:[3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22],
    fileB:'utils/pager.py',      linesB:[10,26], cloneLinesB:[10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26],
    desc:'Near-miss — extra validation and logging statements inserted',
    codeA: [
      { n:3,  text:"def paginate(queryset, page, page_size=20):" },
      { n:4,  text:"    total = queryset.count()" },
      { n:5,  text:"    total_pages = (total + page_size - 1) // page_size" },
      { n:6,  text:"    start = (page - 1) * page_size" },
      { n:7,  text:"    end = start + page_size" },
      { n:8,  text:"    items = queryset[start:end]" },
      { n:9,  text:"    return {" },
      { n:10, text:"        'items': list(items)," },
      { n:11, text:"        'total': total," },
      { n:12, text:"        'page': page," },
      { n:13, text:"        'pages': total_pages," },
      { n:14, text:"    }" },
      { n:15, text:"" },
    ],
    codeB: [
      { n:10, text:"def paginate_results(qs, page_num, size=20):" },
      { n:11, text:"    if page_num < 1:                             # ← added" },
      { n:12, text:"        raise ValueError('page must be >= 1')   # ← added" },
      { n:13, text:"    count = qs.count()" },
      { n:14, text:"    num_pages = (count + size - 1) // size" },
      { n:15, text:"    offset = (page_num - 1) * size" },
      { n:16, text:"    limit  = offset + size" },
      { n:17, text:"    records = qs[offset:limit]" },
      { n:18, text:"    logger.debug(f'page {page_num}/{num_pages}') # ← added" },
      { n:19, text:"    return {" },
      { n:20, text:"        'data': list(records)," },
      { n:21, text:"        'count': count," },
      { n:22, text:"        'page': page_num," },
      { n:23, text:"        'total_pages': num_pages," },
      { n:24, text:"        'has_next': page_num < num_pages,       # ← added" },
      { n:25, text:"    }" },
      { n:26, text:"" },
    ],
  },
  {
    id:6, type:'Type-3', similarity:0.81, crossLang:true,
    fileA:'search/binary_search.py', linesA:[1,16], cloneLinesA:[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],
    fileB:'Search.java',             linesB:[5,22], cloneLinesB:[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22],
    desc:'Binary search — modified to return insertion point in Java version',
    codeA: [
      { n:1,  text:"def binary_search(arr, target):" },
      { n:2,  text:"    lo, hi = 0, len(arr) - 1" },
      { n:3,  text:"    while lo <= hi:" },
      { n:4,  text:"        mid = (lo + hi) // 2" },
      { n:5,  text:"        if arr[mid] == target:" },
      { n:6,  text:"            return mid" },
      { n:7,  text:"        elif arr[mid] < target:" },
      { n:8,  text:"            lo = mid + 1" },
      { n:9,  text:"        else:" },
      { n:10, text:"            hi = mid - 1" },
      { n:11, text:"    return -1" },
      { n:12, text:"" },
    ],
    codeB: [
      { n:5,  text:"public static int binarySearch(int[] arr, int target) {" },
      { n:6,  text:"    int lo = 0, hi = arr.length - 1;" },
      { n:7,  text:"    while (lo <= hi) {" },
      { n:8,  text:"        int mid = lo + (hi - lo) / 2; // ← overflow-safe" },
      { n:9,  text:"        if (arr[mid] == target) return mid;" },
      { n:10, text:"        if (arr[mid] < target) lo = mid + 1;" },
      { n:11, text:"        else hi = mid - 1;" },
      { n:12, text:"    }" },
      { n:13, text:"    return -(lo + 1); // ← insertion point, not -1" },
      { n:14, text:"}" },
      { n:15, text:"" },
    ],
  },

  // ── TYPE 4 ──────────────────────────────────────────────────────────
  {
    id:7, type:'Type-4', similarity:0.91, crossLang:true,
    fileA:'auth/login.py',           linesA:[42,54], cloneLinesA:[42,43,44,45,46,47,48,49,50,51,52,53,54],
    fileB:'services/user_auth.java', linesB:[118,130], cloneLinesB:[118,119,120,121,122,123,124,125,126,127,128,129,130],
    desc:'JWT validation — different syntax, identical functional behaviour',
    codeA: [
      { n:42, text:"def validate_token(token, secret):" },
      { n:43, text:"    try:" },
      { n:44, text:"        payload = jwt.decode(" },
      { n:45, text:"            token, secret," },
      { n:46, text:"            algorithms=['HS256'])" },
      { n:47, text:"        return payload['user_id']" },
      { n:48, text:"    except jwt.ExpiredSignatureError:" },
      { n:49, text:"        raise AuthError('token expired')" },
      { n:50, text:"    except jwt.InvalidTokenError:" },
      { n:51, text:"        raise AuthError('invalid token')" },
      { n:52, text:"    except Exception:" },
      { n:53, text:"        return None" },
      { n:54, text:"" },
    ],
    codeB: [
      { n:118, text:"public String validateToken(String token) {" },
      { n:119, text:"    try {" },
      { n:120, text:"        Claims claims = Jwts.parser()" },
      { n:121, text:"            .setSigningKey(secret)" },
      { n:122, text:"            .parseClaimsJws(token)" },
      { n:123, text:"            .getBody();" },
      { n:124, text:"        return claims.getSubject();" },
      { n:125, text:"    } catch (ExpiredJwtException e) {" },
      { n:126, text:"        throw new AuthException(\"token expired\");" },
      { n:127, text:"    } catch (JwtException e) {" },
      { n:128, text:"        throw new AuthException(\"invalid token\");" },
      { n:129, text:"    } catch (Exception e) { return null; }" },
      { n:130, text:"}" },
    ],
  },
  {
    id:8, type:'Type-4', similarity:0.87, crossLang:true,
    fileA:'utils/sort.py',      linesA:[12,20], cloneLinesA:[12,13,14,15,16,17,18,19,20],
    fileB:'helpers/sorting.js', linesB:[8,15],  cloneLinesB:[8,9,10,11,12,13,14,15],
    desc:'Quicksort — Python list comprehension vs JavaScript functional style',
    codeA: [
      { n:12, text:"def quicksort(arr):" },
      { n:13, text:"    if len(arr) <= 1:" },
      { n:14, text:"        return arr" },
      { n:15, text:"    pivot = arr[len(arr) // 2]" },
      { n:16, text:"    left  = [x for x in arr if x < pivot]" },
      { n:17, text:"    mid   = [x for x in arr if x == pivot]" },
      { n:18, text:"    right = [x for x in arr if x > pivot]" },
      { n:19, text:"    return quicksort(left) + mid + quicksort(right)" },
      { n:20, text:"" },
    ],
    codeB: [
      { n:8,  text:"function quickSort(arr) {" },
      { n:9,  text:"    if (arr.length <= 1) return arr;" },
      { n:10, text:"    const pivot = arr[Math.floor(arr.length / 2)];" },
      { n:11, text:"    const left  = arr.filter(x => x < pivot);" },
      { n:12, text:"    const mid   = arr.filter(x => x === pivot);" },
      { n:13, text:"    const right = arr.filter(x => x > pivot);" },
      { n:14, text:"    return [...quickSort(left), ...mid, ...quickSort(right)];" },
      { n:15, text:"}" },
    ],
  },
]

export const BENCHMARK = [
  { tool:'Proposed System ★', approach:'Hybrid Token + CodeBERT', p:0.89, r:0.93, f1:0.91, time:4.2,  proposed:true  },
  { tool:'SourcererCC',       approach:'Token-based',             p:0.71, r:0.63, f1:0.67, time:12.8, proposed:false },
  { tool:'Deckard',           approach:'AST-based',               p:0.74, r:0.68, f1:0.71, time:28.4, proposed:false },
  { tool:'CDLH',              approach:'AST + LSTM',              p:0.79, r:0.75, f1:0.77, time:67.1, proposed:false },
  { tool:'CodeBERT (solo)',   approach:'Transformer',             p:0.84, r:0.86, f1:0.85, time:9.1,  proposed:false },
]

export const WEEKLY = [
  { day:'Mon', v:18 },{ day:'Tue', v:32 },{ day:'Wed', v:27 },
  { day:'Thu', v:45 },{ day:'Fri', v:38 },{ day:'Sat', v:52 },{ day:'Sun', v:61 },
]

export const DIST = [
  { type:'Type-1 · Exact',    pct:8,  color:'#10b981' },
  { type:'Type-2 · Renamed',  pct:18, color:'#00d4ff' },
  { type:'Type-3 · Near-miss',pct:32, color:'#f59e0b' },
  { type:'Type-4 · Semantic', pct:42, color:'#8b5cf6' },
]

export const EXTS = ['.py', '.java', '.js', '.ts', '.cpp', '.cs']
export const LANGS = ['Auto-detect','Python','Java','JavaScript','C++','C#','TypeScript']
